In [34]:
import HW3
import numpy as np
import math
from pprint import pprint

# shared config

In [2]:
K = 100
r = 0.1
T = 0.5
simCnt = 100000
repeatCnt = 20
S0_i = 95
q_i = 0.05
sigma_i = 0.5

# quesiton 1

In [3]:
assetCnt = 2
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = [[1, 0.9999999],[0.9999999,1]]

In [4]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [5]:
test.sim('')

[[1.         0.00125807]
 [0.00125807 1.        ]]


In [6]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.       , 0.9999999],
       [0.9999999, 1.       ]])

In [7]:
test.answer()

mean: 11.987275439313098 std: 0.07649748817066543
11.834280462971767 11.987275439313098 12.14027041565443


# with antithetic

In [8]:
test.sim('bonus1')

[[1.         0.00411243]
 [0.00411243 1.        ]]


In [9]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.       , 0.9999999],
       [0.9999999, 1.       ]])

In [10]:
test.answer()

mean: 11.981418379007494 std: 0.010948175603967358
11.959522027799558 11.981418379007494 12.003314730215429


# antithetic + inv charloskey

In [11]:
test.sim('bonus2')

[[ 1.00000000e+00 -7.90034704e-18]
 [-7.90034704e-18  1.00000000e+00]]


In [12]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.       , 0.9999999],
       [0.9999999, 1.       ]])

In [13]:
test.answer()

mean: 11.981416330317495 std: 0.010946818657743574
11.959522693002008 11.981416330317495 12.003309967632983


# quesiton 2

In [14]:
assetCnt = 2
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = [[1, -0.9999999],[-0.9999999,1]]

In [15]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [16]:
test.sim('')

[[ 1.         -0.00628842]
 [-0.00628842  1.        ]]


In [17]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1.       , -0.9999999],
       [-0.9999999,  1.       ]])

In [18]:
test.answer()

mean: 23.949208127648955 std: 0.0944810153288653
23.760246096991224 23.949208127648955 24.138170158306686


# with antithetic

In [19]:
test.sim('bonus1')

[[ 1.         -0.00677266]
 [-0.00677266  1.        ]]


In [20]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1.       , -0.9999999],
       [-0.9999999,  1.       ]])

In [21]:
test.answer()

mean: 23.950463909363435 std: 0.014013740068569518
23.922436429226295 23.950463909363435 23.978491389500576


# antithetic + inv charloskey

In [22]:
test.sim('bonus2')

[[ 1.00000000e+00 -1.07369669e-17]
 [-1.07369669e-17  1.00000000e+00]]


In [23]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1.       , -0.9999999],
       [-0.9999999,  1.       ]])

In [24]:
test.answer()

mean: 23.950458373989186 std: 0.014018710593450926
23.922420952802284 23.950458373989186 23.978495795176087


# quesiton 3

In [30]:
assetCnt = 5
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = (np.ones((5,5)) * 0.5) + np.diag([0.5]*5)

In [31]:
print(corrMatrix)

[[1.  0.5 0.5 0.5 0.5]
 [0.5 1.  0.5 0.5 0.5]
 [0.5 0.5 1.  0.5 0.5]
 [0.5 0.5 0.5 1.  0.5]
 [0.5 0.5 0.5 0.5 1. ]]


In [32]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [33]:
test.sim('')

[[ 1.00000000e+00  7.52211765e-04  7.23034112e-04  1.88522033e-03
   8.76917943e-05]
 [ 7.52211765e-04  1.00000000e+00  4.24000592e-04 -2.36950030e-03
  -2.57658379e-03]
 [ 7.23034112e-04  4.24000592e-04  1.00000000e+00  1.65740497e-03
  -2.94350383e-03]
 [ 1.88522033e-03 -2.36950030e-03  1.65740497e-03  1.00000000e+00
  -1.44771476e-03]
 [ 8.76917943e-05 -2.57658379e-03 -2.94350383e-03 -1.44771476e-03
   1.00000000e+00]]


In [35]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.        , 0.50030255, 0.50006036, 0.50116882, 0.50158022],
       [0.50030255, 1.        , 0.50058742, 0.49872999, 0.50080338],
       [0.50006036, 0.50058742, 1.        , 0.50139957, 0.50068787],
       [0.50116882, 0.49872999, 0.50139957, 1.        , 0.49751572],
       [0.50158022, 0.50080338, 0.50068787, 0.49751572, 1.        ]])

In [36]:
test.answer()

mean: 30.364528613980646 std: 0.07888288297541525
30.206762848029815 30.364528613980646 30.522294379931477


# with antithetic

In [37]:
test.sim('bonus1')

[[ 1.         -0.00392724  0.00754789  0.0057971  -0.00419087]
 [-0.00392724  1.         -0.00330494 -0.00236351  0.00159944]
 [ 0.00754789 -0.00330494  1.          0.00277396  0.00419435]
 [ 0.0057971  -0.00236351  0.00277396  1.         -0.00738983]
 [-0.00419087  0.00159944  0.00419435 -0.00738983  1.        ]]


In [38]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.        , 0.49898071, 0.50028739, 0.4970936 , 0.49536168],
       [0.49898071, 1.        , 0.50255256, 0.49670267, 0.49704941],
       [0.50028739, 0.50255256, 1.        , 0.49937423, 0.49858769],
       [0.4970936 , 0.49670267, 0.49937423, 1.        , 0.49436353],
       [0.49536168, 0.49704941, 0.49858769, 0.49436353, 1.        ]])

In [39]:
test.answer()

mean: 30.370494712160507 std: 0.029181613847822613
30.312131484464864 30.370494712160507 30.42885793985615


# antithetic + inv charloskey

In [40]:
test.sim('bonus2')

[[ 1.00000000e+00  3.90976140e-17 -1.54951607e-16 -5.27844435e-17
   3.93862720e-17]
 [ 3.90976140e-17  1.00000000e+00  3.05266923e-17  1.54543045e-18
  -3.90798505e-19]
 [-1.54951607e-16  3.05266923e-17  1.00000000e+00  2.93631786e-17
   4.22928359e-17]
 [-5.27844435e-17  1.54543045e-18  2.93631786e-17  1.00000000e+00
   9.45021839e-18]
 [ 3.93862720e-17 -3.90798505e-19  4.22928359e-17  9.45021839e-18
   1.00000000e+00]]


In [41]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1. , 0.5, 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 1. ]])

In [42]:
test.answer()

mean: 30.376699015909434 std: 0.01977900071782969
30.337141014473776 30.376699015909434 30.416257017345092
