In [45]:
import HW3
import numpy as np
import math
from pprint import pprint

# shared config

In [46]:
K = 100
r = 0.1
T = 0.5
simCnt = 100000
repeatCnt = 20
S0_i = 95
q_i = 0.05
sigma_i = 0.5

# quesiton 1

In [47]:
assetCnt = 2
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = [[1, 1],[1,1]]

In [48]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [49]:
test.sim('')

[[ 1.         -0.00133589]
 [-0.00133589  1.        ]]


In [50]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1., 1.],
       [1., 1.]])

In [51]:
test.answer()

mean: 12.003592875259809 std: 0.07709179400430526
11.849409287251198 12.003592875259809 12.15777646326842


# with antithetic

In [52]:
test.sim('bonus1')

[[1.        0.0017618]
 [0.0017618 1.       ]]


In [53]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1., 1.],
       [1., 1.]])

In [54]:
test.answer()

mean: 11.974212495946151 std: 0.01064562732078666
11.952921241304578 11.974212495946151 11.995503750587725


# antithetic + inv charloskey

In [55]:
test.sim('bonus2')

[[ 1.00000000e+00 -9.76108083e-18]
 [-9.76108083e-18  1.00000000e+00]]


In [56]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1., 1.],
       [1., 1.]])

In [57]:
test.answer()

mean: 11.974212495946155 std: 0.010645627320786655
11.952921241304582 11.974212495946155 11.995503750587728


# quesiton 2

In [22]:
assetCnt = 2
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = [[1, -1],[-1,1]]

In [23]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [24]:
test.sim('')

[[1.         0.00143072]
 [0.00143072 1.        ]]


In [25]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1., -1.],
       [-1.,  1.]])

In [26]:
test.answer()

mean: 23.944352421552765 std: 0.08295713025643667
23.77843816103989 23.944352421552765 24.11026668206564


# with antithetic

In [27]:
test.sim('bonus1')

[[1.         0.00191204]
 [0.00191204 1.        ]]


In [28]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1., -1.],
       [-1.,  1.]])

In [29]:
test.answer()

mean: 23.952184744038 std: 0.015206087562925364
23.92177256891215 23.952184744038 23.98259691916385


# antithetic + inv charloskey

In [30]:
test.sim('bonus2')

[[1.00000000e+00 2.35900188e-17]
 [2.35900188e-17 1.00000000e+00]]


In [31]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[ 1., -1.],
       [-1.,  1.]])

In [32]:
test.answer()

mean: 23.952184744038 std: 0.015206087562924978
23.92177256891215 23.952184744038 23.98259691916385


# quesiton 3

In [58]:
assetCnt = 5
S0Lst = [S0_i] * assetCnt
qLst = [q_i] * assetCnt
sigmaLst = [sigma_i] * assetCnt
corrMatrix = (np.ones((5,5)) * 0.5) + np.diag([0.5]*5)

In [59]:
print(corrMatrix)

[[1.  0.5 0.5 0.5 0.5]
 [0.5 1.  0.5 0.5 0.5]
 [0.5 0.5 1.  0.5 0.5]
 [0.5 0.5 0.5 1.  0.5]
 [0.5 0.5 0.5 0.5 1. ]]


In [60]:
test = HW3.rainbow_mcSim(K, r, T, assetCnt, S0Lst, qLst, sigmaLst, corrMatrix, simCnt, repeatCnt)

# without antithetic

In [61]:
test.sim('')

[[ 1.00000000e+00  2.53052196e-03  1.02183743e-03  3.65875739e-03
   2.59603101e-03]
 [ 2.53052196e-03  1.00000000e+00  2.59875079e-03 -2.40275318e-03
   3.18079616e-03]
 [ 1.02183743e-03  2.59875079e-03  1.00000000e+00 -2.96762808e-04
   2.52904886e-03]
 [ 3.65875739e-03 -2.40275318e-03 -2.96762808e-04  1.00000000e+00
  -9.60828545e-04]
 [ 2.59603101e-03  3.18079616e-03  2.52904886e-03 -9.60828545e-04
   1.00000000e+00]]


In [62]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.        , 0.4981667 , 0.49611668, 0.49803024, 0.49983663],
       [0.4981667 , 1.        , 0.50073785, 0.50051438, 0.50004902],
       [0.49611668, 0.50073785, 1.        , 0.50423548, 0.49979083],
       [0.49803024, 0.50051438, 0.50423548, 1.        , 0.49823721],
       [0.49983663, 0.50004902, 0.49979083, 0.49823721, 1.        ]])

In [63]:
test.answer()

mean: 30.404013508036904 std: 0.09937897063802419
30.205255566760854 30.404013508036904 30.602771449312954


# with antithetic

In [64]:
test.sim('bonus1')

[[ 1.00000000e+00  5.91888665e-03  2.63140260e-03 -8.89617367e-04
   3.32619082e-03]
 [ 5.91888665e-03  1.00000000e+00 -1.86424669e-03 -2.16041275e-03
   7.16092048e-03]
 [ 2.63140260e-03 -1.86424669e-03  1.00000000e+00 -5.66037876e-03
  -3.35291404e-03]
 [-8.89617367e-04 -2.16041275e-03 -5.66037876e-03  1.00000000e+00
   1.76440920e-03]
 [ 3.32619082e-03  7.16092048e-03 -3.35291404e-03  1.76440920e-03
   1.00000000e+00]]


In [65]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1.        , 0.49964224, 0.50012132, 0.50013408, 0.50144405],
       [0.49964224, 1.        , 0.50469557, 0.50338387, 0.50445623],
       [0.50012132, 0.50469557, 1.        , 0.50841902, 0.50271524],
       [0.50013408, 0.50338387, 0.50841902, 1.        , 0.50184215],
       [0.50144405, 0.50445623, 0.50271524, 0.50184215, 1.        ]])

In [66]:
test.answer()

mean: 30.37719950320986 std: 0.02374130842698581
30.329716886355886 30.37719950320986 30.42468212006383


# antithetic + inv charloskey

In [67]:
test.sim('bonus2')

[[ 1.00000000e+00 -5.96855898e-18 -1.10134124e-17  1.13242749e-17
  -3.22941673e-17]
 [-5.96855898e-18  1.00000000e+00  8.02913291e-18  2.19047003e-17
  -6.20303808e-17]
 [-1.10134124e-17  8.02913291e-18  1.00000000e+00  3.11750625e-17
   1.38200562e-17]
 [ 1.13242749e-17  2.19047003e-17  3.11750625e-17  1.00000000e+00
   2.40696352e-18]
 [-3.22941673e-17 -6.20303808e-17  1.38200562e-17  2.40696352e-18
   1.00000000e+00]]


In [68]:
np.corrcoef(test.simulator.result[0], rowvar = False)

array([[1. , 0.5, 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 1. ]])

In [69]:
test.answer()

mean: 30.37852373976275 std: 0.025332122743533372
30.327859494275682 30.37852373976275 30.429187985249815
